language: python

cache: pip

python:
    - 2.7
    - 3.4
    - 3.5
    - "3.5-dev"
    - 3.6
    - "3.6-dev"
    - "3.7-dev"
    - "nightly"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install gcc python-socksipy libssl-dev swig -qq
    - wget http://downloads.sourceforge.net/project/ssdeep/ssdeep-2.10/ssdeep-2.10.tar.gz
    - tar -zxvf ssdeep-2.10.tar.gz
    - pushd ssdeep-2.10
    - ./configure && make
    - sudo make install
<<<<<<< HEAD
    - popd
||||||| parent of a74ed90... pep8 fixes, add license - commit squash
    - cd ..
    - git pull --recurse-submodules && git submodule update
=======
    - cd ..
<<<<<<< HEAD
    - git config user.email "travis@example.com"
    - git config user.name "Travis"
    - git pull --recurse-submodules --no-commit
    - git submodule update

>>>>>>> a74ed90... pep8 fixes, add license - commit squash
||||||| parent of 5302faa... Initial refactoring for python3 support
    - git config user.email "travis@example.com"
    - git config user.name "Travis"
    - git pull --recurse-submodules --no-commit
    - git submodule update

=======
    - git pull --recurse-submodules && git submodule update
>>>>>>> 5302faa... Initial refactoring for python3 support
install:
    - pip install -r requirements-dev.txt
script:
    - echo "exit" | python viper-cli
